# This is a basic workflow to help you get started with Actions

name: CI_test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Rename spaces
        run: |
          ls
          Rename-Item -Path "test test test.txt" -NewName "test_test_test.txt"
          echo ---------------
          ls

      # Runs a set of commands using the runners shell
      - name: find file and path
        run: |
          
          ls
          Get-ChildItem -Path ./build/release -Recurse -Include *.exe
          #echo $path



      - name: Archive  artifact
        uses: actions/upload-artifact@v3
        with:
          name: test_test
          path: "test_test_test.txt"

      - name: Archive space  artifact
        uses: actions/upload-artifact@v3
        with:
          name: test_test
          path: "test test test.txt"
