# This is a basic workflow to help you get started with Actions

name: CI_test
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      deploy_env:
        type: 'choice'
        description: Choose deploying environment
        required: true
        default: Dev
        options:
           - Prod
           - Dev   

jobs:
  build:
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell

      - name: Set deploy env Prod
        if: "${{ github.event.inputs.deploy_env == 'Prod' }}"
        run: |
          echo "path=desktop-recorder" >> "electron-builder.env"
          echo "Check env file:"
          Get-Content -Path .\electron-builder.env
          
      - name: Set deploy env Dev
        if: "${{ github.event.inputs.deploy_env == null || github.event.inputs.deploy_env == 'Dev' }}"
        run: |
          echo "path=canary-desktop-recorder" >> "electron-builder.env"
          echo "Check env file:"
          Get-Content -Path .\electron-builder.env
          

      - name: Set env var
        run: |
          echo "2 $github.env"
          echo "VAR1=${{ secrets.TEST }}" >> "$github.env"
          echo ________________
          echo $VAR 
      
      - name: Rename spaces
        run: |
          Rename-Item -Path "test test test.txt" -NewName "test_test_test.txt"
          echo ---------------
          ls
          echo ________________
          echo ${{ secrets.TEST }}
          $VAR="${{ secrets.TEST }}"
          echo ________________
          echo "$VAR"
          echo "$VAR1"
          echo "${{env.VAR1}}"





      # Runs a set of commands using the runners shell
      - name: find file and path
        run: |
          ${file}= Get-ChildItem -Path ./build/release/*.exe | % { $_.FullName }
          echo ---------------------------
          echo "${file}"
          echo "file_path=${file}" > .env
          Get-Content -Path ".\.env"
          echo ---------------------------
          echo "${{ github.workspace }}/build/release/"

          #echo "Log level: ${{ github.event.inputs.deploy_env }}"
          #echo ${{ inputs.deploy_env }}

      - name: Testing vars
        run: |
          ${file}= Get-ChildItem -Path ./build/release/*.exe | % { $_.FullName }
          echo "Var: ${file}"
          echo "env var: ${{ env.file_path }}"
          echo ---------------------------
          echo "${{ github.workspace }}/build/release/"

      - name: Archive  artifact
        uses: actions/upload-artifact@v3
        with:
          name: test_test
          path: "test_test_test.txt"

      - name: Archive space  artifact
        uses: actions/upload-artifact@v3
        with:
          name: test_test
          path: "test test test.txt"
