# This is a basic workflow to help you get started with Actions

name: CI_test
on:

  workflow_dispatch:
    inputs:
      deploy_env:
        type: choice
        description: Choose deploying environment
        options:
           - Prod
           - Dev   

jobs:
  build:
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell

      - name: Set env var
        run: |
          echo "VAR=${{ secrets.TEST }}" >> "$GITHUB_ENV"
          echo ________________
          echo $VAR 
      
      - name: Rename spaces
        run: |
          ls
          Rename-Item -Path "test test test.txt" -NewName "test_test_test.txt"
          echo ---------------
          ls
          echo ________________
          echo ${{env.VAR}}
          echo ${{ secrets.TEST }}
          echo ________________
          echo $VAR 

        
          
          

      # Runs a set of commands using the runners shell
      - name: find file and path
        run: |
          $file= Get-ChildItem -Path ./build/release/*.exe | % { $_.FullName }
          echo ---------------------------
          echo $file

          echo "Log level: ${{ github.event.inputs.deploy_env }}"
          echo ${{ inputs.deploy_env }}



      - name: Archive  artifact
        uses: actions/upload-artifact@v3
        with:
          name: test_test
          path: "test_test_test.txt"

      - name: Archive space  artifact
        uses: actions/upload-artifact@v3
        with:
          name: test_test
          path: "test test test.txt"
