name: Test_Second
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      deploy_env:
        type: choice
        description: Choose deploying environment
        options:
           - Prod
           - Dev   

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: |
          echo "${{ secrets.SECRET }}" > .env
          echo -----
          ls
          echo -----
          cat .env | sed 's/./& /g'
          echo --------------------------------------
          echo --------------------------------------
          echo "$secret_test" > .env1
          echo -----
          cat .env1 | sed 's/./& /g'
          echo --------------------------------------
          echo --------------------------------------
          echo "$env.secret_test" > .env2
          echo -----
          cat .env2 | sed 's/./& /g'
          echo --------------------------------------


          
        env:
          secret_test: ${{ secrets.SECRET }}
          secret_test1: ${{ secrets.SECRET1231 }}
