name: Test_Second
on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: |
          echo "$secret_test" > .env
          echo -----
          ls
          echo -----
          cat .env | sed 's/./& /g'
          echo -----
        env:
          secret_test: ${{ secrets.SECRET }}
